language: node_js
node_js:
  - "stable"

script:
  - npm install
  - npm test
  - npm run build
// this is used to cashes all dependencies first time ,so to speed up
//deploment next time
cache:
  dependencies: node_modules

deploy:
  provider: surge
  skip_cleanup: true
  domain: recondite-birth.surge.sh
  project: ./build/

on:
  branch: master
